name: Format Python code
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install black and isort
        run: pip install black isort
      - name: Test if black and isort should reformat the scripts
        id: black_isort_status
        run: |
          if black --check nqp/ && isort --check-only nqp/; then
            echo "::set-output name=result::false"
          else
            echo "::set-output name=result::true"
          fi
      - name: If needed, commit black/isort changes to the pull request
        if: steps.black_isort_status.outputs.result == 'true'
        run: |
          black "nqp/"
          isort "nqp/"
          git config --global user.name "Snayff"
          git config --global user.email "Snayff@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
          git fetch
          git checkout "$GITHUB_HEAD_REF"
          git commit -am "nqp formatted code with black and isort"
          git push
