name: Run Tests
on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.0

    - name: Run test suite
      run: |
        poetry run python -m pytest